// Generated by CongoCC Parser Generator. Do not edit.

use crate::tokens::TokenType;
use std::fmt;

/// Error type for parse and lex failures.
///
/// Contains a human-readable message, source location information,
/// the set of expected token types, the token type actually found,
/// and the parser production call stack at the point of failure.
///
/// # Examples
///
/// ```
/// use org_parsers_lua::error::ParseError;
///
/// let err = ParseError::new("unexpected end of input".to_string());
/// assert!(format!("{}", err).contains("unexpected end of input"));
/// ```
#[derive(Debug, Clone)]
pub struct ParseError {
    /// Human-readable description of the error.
    pub message: String,
    /// 1-based line number where the error occurred, if known.
    pub line: usize,
    /// 1-based column number where the error occurred, if known.
    pub column: usize,
    /// Source name (e.g., filename) associated with this error.
    pub source_name: String,
    /// The token types that were expected at the error location.
    pub expected: Vec<TokenType>,
    /// The token type that was actually found, if any.
    pub found: Option<TokenType>,
    /// The parser production call stack at the point of failure,
    /// from innermost (current) to outermost.
    pub production_stack: Vec<String>,
}

impl ParseError {
    /// Creates a new parse error with only a message.
    ///
    /// Location fields default to line 0, column 0, empty source name.
    pub fn new(message: String) -> Self {
        Self {
            message,
            line: 0,
            column: 0,
            source_name: String::new(),
            expected: Vec::new(),
            found: None,
            production_stack: Vec::new(),
        }
    }

    /// Creates a parse error at a specific source location.
    pub fn at(message: String, source_name: &str, line: usize, column: usize) -> Self {
        Self {
            message,
            line,
            column,
            source_name: source_name.to_string(),
            expected: Vec::new(),
            found: None,
            production_stack: Vec::new(),
        }
    }

    /// Creates a parse error for an unexpected token, including the
    /// set of expected token types.
    pub fn unexpected_token(
        found: TokenType,
        found_text: &str,
        source_name: &str,
        line: usize,
        column: usize,
        expected: &[TokenType],
    ) -> Self {
        let expected_str: Vec<String> = expected.iter().map(|t| format!("{}", t)).collect();
        let message = if expected.is_empty() {
            format!(
                "Unexpected token {} ({:?}) at line {}, column {}",
                found, found_text, line, column,
            )
        } else {
            format!(
                "Expected one of [{}], but found {} ({:?}) at line {}, column {}",
                expected_str.join(", "),
                found,
                found_text,
                line,
                column,
            )
        };
        Self {
            message,
            line,
            column,
            source_name: source_name.to_string(),
            expected: expected.to_vec(),
            found: Some(found),
            production_stack: Vec::new(),
        }
    }

    /// Adds a production name to the call stack context.
    pub fn with_production(mut self, production: &str) -> Self {
        self.production_stack.push(production.to_string());
        self
    }
}

impl fmt::Display for ParseError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // Format: [source_name:line:col] message
        //         in: Production1 > Production2
        if !self.source_name.is_empty() {
            write!(f, "[{}:", self.source_name)?;
            if self.line > 0 {
                write!(f, "{}:{}", self.line, self.column)?;
            }
            write!(f, "] ")?;
        } else if self.line > 0 {
            write!(f, "line {}, col {}: ", self.line, self.column)?;
        }
        write!(f, "{}", self.message)?;
        if !self.production_stack.is_empty() {
            write!(f, "\n  in: {}", self.production_stack.join(" > "))?;
        }
        Ok(())
    }
}

impl std::error::Error for ParseError {}

/// A convenience type alias for parse results.
pub type ParseResult<T> = Result<T, ParseError>;
