// Generated by CongoCC Parser Generator. Do not edit.

/// Token types for this grammar.
///
/// Each variant corresponds to a token defined in the grammar specification.
/// The discriminant values match the order in which tokens are defined,
/// enabling efficient set membership tests.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u16)]
pub enum TokenType {
    EOF = 0,
    SEMICOLON = 1,
    COMMA = 2,
    LPAREN = 3,
    RPAREN = 4,
    LBRACE = 5,
    RBRACE = 6,
    LBRACKET = 7,
    RBRACKET = 8,
    ASSIGN = 9,
    LT = 10,
    LE = 11,
    GT = 12,
    GE = 13,
    COLON = 14,
    DOUBLE_COLON = 15,
    DOT = 16,
    ELLIPSIS = 17,
    HAT = 18,
    NE = 19,
    EQ = 20,
    STR_CAT = 21,
    PLUS = 22,
    MINUS = 23,
    TIMES = 24,
    SLASH = 25,
    DOUBLE_SLASH = 26,
    MOD = 27,
    BIT_OR = 28,
    BIT_AND = 29,
    TILDE = 30,
    LSHIFT = 31,
    RSHIFT = 32,
    HASH = 33,
    OR = 34,
    AND = 35,
    NOT = 36,
    BREAK = 37,
    DO = 38,
    ELSE = 39,
    ELSEIF = 40,
    END = 41,
    FALSE = 42,
    FOR = 43,
    FUNCTION = 44,
    GOTO = 45,
    IF = 46,
    IN = 47,
    LOCAL = 48,
    NIL = 49,
    REPEAT = 50,
    RETURN = 51,
    THEN = 52,
    TRUE = 53,
    UNTIL = 54,
    WHILE = 55,
    SINGLE_LINE_COMMENT_START = 56,
    NORMALSTRING = 57,
    CHARSTRING = 58,
    INT = 59,
    HEX = 60,
    FLOAT = 61,
    HEX_FLOAT = 62,
    NAME = 63,
    SHEBANG = 64,
    WS = 65,
    MULTILINE_START = 66,
    LONGSTRING_START = 67,
    LINE_COMMENT = 68,
    MULTILINE_COMMENT = 69,
    LONGSTRING = 70,
    ANY_CHAR = 71,
    /// Sentinel for the end of a sequence of tokens with no more pending.
    DUMMY = 72,
    /// Placeholder for invalid/unrecognized input.
    INVALID = 73,
}

impl TokenType {
    /// Total number of defined token types (excluding DUMMY and INVALID).
    pub const COUNT: usize = 72;

    /// Returns `true` if this token type is a regular (parsing) token.
    pub fn is_regular(self) -> bool {
        matches!(self,
            TokenType::EOF |
            TokenType::SEMICOLON |
            TokenType::COMMA |
            TokenType::LPAREN |
            TokenType::RPAREN |
            TokenType::LBRACE |
            TokenType::RBRACE |
            TokenType::LBRACKET |
            TokenType::RBRACKET |
            TokenType::ASSIGN |
            TokenType::LT |
            TokenType::LE |
            TokenType::GT |
            TokenType::GE |
            TokenType::COLON |
            TokenType::DOUBLE_COLON |
            TokenType::DOT |
            TokenType::ELLIPSIS |
            TokenType::HAT |
            TokenType::NE |
            TokenType::EQ |
            TokenType::STR_CAT |
            TokenType::PLUS |
            TokenType::MINUS |
            TokenType::TIMES |
            TokenType::SLASH |
            TokenType::DOUBLE_SLASH |
            TokenType::MOD |
            TokenType::BIT_OR |
            TokenType::BIT_AND |
            TokenType::TILDE |
            TokenType::LSHIFT |
            TokenType::RSHIFT |
            TokenType::HASH |
            TokenType::OR |
            TokenType::AND |
            TokenType::NOT |
            TokenType::BREAK |
            TokenType::DO |
            TokenType::ELSE |
            TokenType::ELSEIF |
            TokenType::END |
            TokenType::FALSE |
            TokenType::FOR |
            TokenType::FUNCTION |
            TokenType::GOTO |
            TokenType::IF |
            TokenType::IN |
            TokenType::LOCAL |
            TokenType::NIL |
            TokenType::REPEAT |
            TokenType::RETURN |
            TokenType::THEN |
            TokenType::TRUE |
            TokenType::UNTIL |
            TokenType::WHILE |
            TokenType::NORMALSTRING |
            TokenType::CHARSTRING |
            TokenType::INT |
            TokenType::HEX |
            TokenType::FLOAT |
            TokenType::HEX_FLOAT |
            TokenType::NAME |
            TokenType::SHEBANG |
            TokenType::LONGSTRING)
    }

    /// Returns `true` if this token type is skipped (e.g., whitespace, comments).
    pub fn is_skipped(self) -> bool {
        matches!(self,
            TokenType::WS)
    }

    /// Returns `true` if this token type is unparsed (SPECIAL_TOKEN / UNPARSED).
    pub fn is_unparsed(self) -> bool {
        matches!(self,
            TokenType::LINE_COMMENT |
            TokenType::MULTILINE_COMMENT)
    }

    /// Returns `true` if this token type is a MORE token (pending additional input).
    pub fn is_more(self) -> bool {
        matches!(self,
            TokenType::SINGLE_LINE_COMMENT_START |
            TokenType::MULTILINE_START |
            TokenType::LONGSTRING_START |
            TokenType::ANY_CHAR)
    }
}

impl std::fmt::Display for TokenType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            TokenType::EOF => write!(f, "EOF"),
            TokenType::SEMICOLON => write!(f, "SEMICOLON"),
            TokenType::COMMA => write!(f, "COMMA"),
            TokenType::LPAREN => write!(f, "LPAREN"),
            TokenType::RPAREN => write!(f, "RPAREN"),
            TokenType::LBRACE => write!(f, "LBRACE"),
            TokenType::RBRACE => write!(f, "RBRACE"),
            TokenType::LBRACKET => write!(f, "LBRACKET"),
            TokenType::RBRACKET => write!(f, "RBRACKET"),
            TokenType::ASSIGN => write!(f, "ASSIGN"),
            TokenType::LT => write!(f, "LT"),
            TokenType::LE => write!(f, "LE"),
            TokenType::GT => write!(f, "GT"),
            TokenType::GE => write!(f, "GE"),
            TokenType::COLON => write!(f, "COLON"),
            TokenType::DOUBLE_COLON => write!(f, "DOUBLE_COLON"),
            TokenType::DOT => write!(f, "DOT"),
            TokenType::ELLIPSIS => write!(f, "ELLIPSIS"),
            TokenType::HAT => write!(f, "HAT"),
            TokenType::NE => write!(f, "NE"),
            TokenType::EQ => write!(f, "EQ"),
            TokenType::STR_CAT => write!(f, "STR_CAT"),
            TokenType::PLUS => write!(f, "PLUS"),
            TokenType::MINUS => write!(f, "MINUS"),
            TokenType::TIMES => write!(f, "TIMES"),
            TokenType::SLASH => write!(f, "SLASH"),
            TokenType::DOUBLE_SLASH => write!(f, "DOUBLE_SLASH"),
            TokenType::MOD => write!(f, "MOD"),
            TokenType::BIT_OR => write!(f, "BIT_OR"),
            TokenType::BIT_AND => write!(f, "BIT_AND"),
            TokenType::TILDE => write!(f, "TILDE"),
            TokenType::LSHIFT => write!(f, "LSHIFT"),
            TokenType::RSHIFT => write!(f, "RSHIFT"),
            TokenType::HASH => write!(f, "HASH"),
            TokenType::OR => write!(f, "OR"),
            TokenType::AND => write!(f, "AND"),
            TokenType::NOT => write!(f, "NOT"),
            TokenType::BREAK => write!(f, "BREAK"),
            TokenType::DO => write!(f, "DO"),
            TokenType::ELSE => write!(f, "ELSE"),
            TokenType::ELSEIF => write!(f, "ELSEIF"),
            TokenType::END => write!(f, "END"),
            TokenType::FALSE => write!(f, "FALSE"),
            TokenType::FOR => write!(f, "FOR"),
            TokenType::FUNCTION => write!(f, "FUNCTION"),
            TokenType::GOTO => write!(f, "GOTO"),
            TokenType::IF => write!(f, "IF"),
            TokenType::IN => write!(f, "IN"),
            TokenType::LOCAL => write!(f, "LOCAL"),
            TokenType::NIL => write!(f, "NIL"),
            TokenType::REPEAT => write!(f, "REPEAT"),
            TokenType::RETURN => write!(f, "RETURN"),
            TokenType::THEN => write!(f, "THEN"),
            TokenType::TRUE => write!(f, "TRUE"),
            TokenType::UNTIL => write!(f, "UNTIL"),
            TokenType::WHILE => write!(f, "WHILE"),
            TokenType::SINGLE_LINE_COMMENT_START => write!(f, "SINGLE_LINE_COMMENT_START"),
            TokenType::NORMALSTRING => write!(f, "NORMALSTRING"),
            TokenType::CHARSTRING => write!(f, "CHARSTRING"),
            TokenType::INT => write!(f, "INT"),
            TokenType::HEX => write!(f, "HEX"),
            TokenType::FLOAT => write!(f, "FLOAT"),
            TokenType::HEX_FLOAT => write!(f, "HEX_FLOAT"),
            TokenType::NAME => write!(f, "NAME"),
            TokenType::SHEBANG => write!(f, "SHEBANG"),
            TokenType::WS => write!(f, "WS"),
            TokenType::MULTILINE_START => write!(f, "MULTILINE_START"),
            TokenType::LONGSTRING_START => write!(f, "LONGSTRING_START"),
            TokenType::LINE_COMMENT => write!(f, "LINE_COMMENT"),
            TokenType::MULTILINE_COMMENT => write!(f, "MULTILINE_COMMENT"),
            TokenType::LONGSTRING => write!(f, "LONGSTRING"),
            TokenType::ANY_CHAR => write!(f, "ANY_CHAR"),
            TokenType::DUMMY => write!(f, "DUMMY"),
            TokenType::INVALID => write!(f, "INVALID"),
        }
    }
}

/// Returns `true` if this token type is a contextual token.
///
/// This grammar has no contextual tokens.
#[inline]
pub fn is_contextual_token(_tt: TokenType) -> bool {
    false
}

/// Lexical states for this grammar.
///
/// The lexer can operate in different lexical states, each with its own
/// set of NFA transition functions for token recognition.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LexicalState {
    LUA,
    IN_SINGLE_LINE_COMMENT,
    IN_MULTI_LINE,
    IN_LONGSTRING,
}

impl Default for LexicalState {
    fn default() -> Self {
        LexicalState::LUA
    }
}

/// Returns the lexical state to transition to after matching the given token type,
/// or `None` if no transition is defined.
pub fn lexical_state_for(tt: TokenType) -> Option<LexicalState> {
    match tt {
        TokenType::SINGLE_LINE_COMMENT_START => Some(LexicalState::IN_SINGLE_LINE_COMMENT),
        TokenType::MULTILINE_START => Some(LexicalState::IN_MULTI_LINE),
        TokenType::LONGSTRING_START => Some(LexicalState::IN_LONGSTRING),
        TokenType::LINE_COMMENT => Some(LexicalState::LUA),
        TokenType::MULTILINE_COMMENT => Some(LexicalState::LUA),
        TokenType::LONGSTRING => Some(LexicalState::LUA),
        _ => None,
    }
}
