// Generated by CongoCC Parser Generator. Do not edit.

use crate::ast::{Ast, AstBuilder, NodeId, NodeKind, TokenId};
use crate::tokens::TokenType;

// =================================================================
// Read-only Visitor
// =================================================================

/// Read-only depth-first visitor for AST traversal.
///
/// Implement this trait to process AST nodes without modifying the tree.
/// The default implementation of each `visit_*` method calls `visit_children`
/// to continue the depth-first walk.
///
/// # Examples
///
/// ```
/// use org_parsers_lua::visitor::Visitor;
/// use org_parsers_lua::ast::{Ast, NodeId, NodeKind};
///
/// struct NodeCounter { count: usize }
///
/// impl Visitor for NodeCounter {
///     fn default_visit(&mut self, ast: &Ast, id: NodeId) {
///         self.count += 1;
///         self.visit_children(ast, id);
///     }
/// }
///
/// // let ast = Parser::parse(...).unwrap();
/// // let mut counter = NodeCounter { count: 0 };
/// // if let Some(root) = ast.root() {
/// //     counter.visit(&ast, root);
/// // }
/// // println!("Total nodes: {}", counter.count);
/// ```
pub trait Visitor {
    /// Called for any node kind that does not have a specific `visit_*` override.
    fn default_visit(&mut self, ast: &Ast, id: NodeId) {
        self.visit_children(ast, id);
    }

    /// Dispatches to the appropriate `visit_*` method based on node kind.
    fn visit(&mut self, ast: &Ast, id: NodeId) {
        match ast.kind(id) {
            NodeKind::Root => self.visit_root(ast, id),
            NodeKind::Block => self.visit_block(ast, id),
            NodeKind::EmptyStatement => self.visit_emptystatement(ast, id),
            NodeKind::BreakStatement => self.visit_breakstatement(ast, id),
            NodeKind::Statement => self.visit_statement(ast, id),
            NodeKind::Assignment => self.visit_assignment(ast, id),
            NodeKind::DoBlock => self.visit_doblock(ast, id),
            NodeKind::GotoStatement => self.visit_gotostatement(ast, id),
            NodeKind::ForStatement => self.visit_forstatement(ast, id),
            NodeKind::FunctionDeclaration => self.visit_functiondeclaration(ast, id),
            NodeKind::LocalFunctionDeclaration => self.visit_localfunctiondeclaration(ast, id),
            NodeKind::LocalAttributeAssignment => self.visit_localattributeassignment(ast, id),
            NodeKind::IfStatement => self.visit_ifstatement(ast, id),
            NodeKind::RepeatStatement => self.visit_repeatstatement(ast, id),
            NodeKind::WhileStatement => self.visit_whilestatement(ast, id),
            NodeKind::AttributeNameList => self.visit_attributenamelist(ast, id),
            NodeKind::Attribute => self.visit_attribute(ast, id),
            NodeKind::LastStatement => self.visit_laststatement(ast, id),
            NodeKind::Label => self.visit_label(ast, id),
            NodeKind::FunctionName => self.visit_functionname(ast, id),
            NodeKind::VarList => self.visit_varlist(ast, id),
            NodeKind::NameList => self.visit_namelist(ast, id),
            NodeKind::ExpressionList => self.visit_expressionlist(ast, id),
            NodeKind::PrimaryExpression => self.visit_primaryexpression(ast, id),
            NodeKind::PowerExpression => self.visit_powerexpression(ast, id),
            NodeKind::UnaryExpression => self.visit_unaryexpression(ast, id),
            NodeKind::MultiplicativeExpression => self.visit_multiplicativeexpression(ast, id),
            NodeKind::AdditiveExpression => self.visit_additiveexpression(ast, id),
            NodeKind::StringCatExpression => self.visit_stringcatexpression(ast, id),
            NodeKind::ComparisonExpression => self.visit_comparisonexpression(ast, id),
            NodeKind::AndExpression => self.visit_andexpression(ast, id),
            NodeKind::OrExpression => self.visit_orexpression(ast, id),
            NodeKind::Expression => self.visit_expression(ast, id),
            NodeKind::PrefixExp => self.visit_prefixexp(ast, id),
            NodeKind::FunctionCall => self.visit_functioncall(ast, id),
            NodeKind::VarOrExp => self.visit_varorexp(ast, id),
            NodeKind::Var => self.visit_var(ast, id),
            NodeKind::VarSuffix => self.visit_varsuffix(ast, id),
            NodeKind::NameAndArgs => self.visit_nameandargs(ast, id),
            NodeKind::Args => self.visit_args(ast, id),
            NodeKind::FunctionDef => self.visit_functiondef(ast, id),
            NodeKind::FunctionBody => self.visit_functionbody(ast, id),
            NodeKind::ParamList => self.visit_paramlist(ast, id),
            NodeKind::TableConstructor => self.visit_tableconstructor(ast, id),
            NodeKind::FieldList => self.visit_fieldlist(ast, id),
            NodeKind::Field => self.visit_field(ast, id),
            NodeKind::Token(_) => self.visit_token(ast, id),
        }
    }

    /// Visit a `Root` node.
    fn visit_root(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `Block` node.
    fn visit_block(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `EmptyStatement` node.
    fn visit_emptystatement(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `BreakStatement` node.
    fn visit_breakstatement(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `Statement` node.
    fn visit_statement(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `Assignment` node.
    fn visit_assignment(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `DoBlock` node.
    fn visit_doblock(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `GotoStatement` node.
    fn visit_gotostatement(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `ForStatement` node.
    fn visit_forstatement(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `FunctionDeclaration` node.
    fn visit_functiondeclaration(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `LocalFunctionDeclaration` node.
    fn visit_localfunctiondeclaration(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `LocalAttributeAssignment` node.
    fn visit_localattributeassignment(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `IfStatement` node.
    fn visit_ifstatement(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `RepeatStatement` node.
    fn visit_repeatstatement(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `WhileStatement` node.
    fn visit_whilestatement(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `AttributeNameList` node.
    fn visit_attributenamelist(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `Attribute` node.
    fn visit_attribute(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `LastStatement` node.
    fn visit_laststatement(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `Label` node.
    fn visit_label(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `FunctionName` node.
    fn visit_functionname(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `VarList` node.
    fn visit_varlist(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `NameList` node.
    fn visit_namelist(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `ExpressionList` node.
    fn visit_expressionlist(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `PrimaryExpression` node.
    fn visit_primaryexpression(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `PowerExpression` node.
    fn visit_powerexpression(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `UnaryExpression` node.
    fn visit_unaryexpression(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `MultiplicativeExpression` node.
    fn visit_multiplicativeexpression(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `AdditiveExpression` node.
    fn visit_additiveexpression(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `StringCatExpression` node.
    fn visit_stringcatexpression(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `ComparisonExpression` node.
    fn visit_comparisonexpression(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `AndExpression` node.
    fn visit_andexpression(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `OrExpression` node.
    fn visit_orexpression(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `Expression` node.
    fn visit_expression(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `PrefixExp` node.
    fn visit_prefixexp(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `FunctionCall` node.
    fn visit_functioncall(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `VarOrExp` node.
    fn visit_varorexp(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `Var` node.
    fn visit_var(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `VarSuffix` node.
    fn visit_varsuffix(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `NameAndArgs` node.
    fn visit_nameandargs(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `Args` node.
    fn visit_args(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `FunctionDef` node.
    fn visit_functiondef(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `FunctionBody` node.
    fn visit_functionbody(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `ParamList` node.
    fn visit_paramlist(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `TableConstructor` node.
    fn visit_tableconstructor(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `FieldList` node.
    fn visit_fieldlist(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a `Field` node.
    fn visit_field(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visit a token leaf node.
    fn visit_token(&mut self, ast: &Ast, id: NodeId) {
        self.default_visit(ast, id);
    }

    /// Visits all direct children of the given node.
    fn visit_children(&mut self, ast: &Ast, id: NodeId) {
        for child in ast.children(id) {
            self.visit(ast, child);
        }
    }
}

// =================================================================
// Functional AstMapper
// =================================================================

/// Describes what a mapped node becomes in the output AST.
///
/// Returned by each `map_*` method in the `AstMapper` trait to
/// control how the source node is represented in the output.
pub enum MappedNode {
    /// Emit a node with the given kind and children.
    ///
    /// Use the source kind + `mapped_children` for identity (no change).
    /// Use a different kind for node-local type changes.
    /// Use a different children vec for structural changes.
    /// Offsets are recomputed from the children's spans.
    Node {
        kind: NodeKind,
        children: Vec<NodeId>,
    },

    /// Remove this node and splice the given nodes directly into
    /// the parent's child list. Typically pass `mapped_children` to
    /// flatten a wrapper node away.
    Splice(Vec<NodeId>),

    /// Remove this node and all its descendants from the output.
    Remove,
}

/// Functional AST transformation driven by bottom-up traversal.
///
/// The framework walks the source AST in post-order (children before
/// parents). For each node, it maps all children first, then calls
/// the appropriate `map_*` method with:
///
/// - `source_id` — the node's ID in the source AST (for reading
///   context, siblings, ancestors, etc.)
/// - `source` — the complete source AST (read-only)
/// - `mapped_children` — this node's children, already mapped, as
///   `NodeId`s in the output AST being built
/// - `builder` — mutable handle for creating new nodes in the output
///
/// Each method returns a `MappedNode` describing what this node
/// should become. The default implementation preserves the node
/// identity (same kind, same mapped children).
///
/// # Examples
///
/// ```no_run
/// use org_parsers_lua::visitor::{AstMapper, MappedNode};
/// use org_parsers_lua::ast::{Ast, AstBuilder, NodeId, NodeKind};
///
/// struct RemoveNulls;
///
/// impl AstMapper for RemoveNulls {
///     // Override specific map methods to transform the tree.
///     // All other node types pass through unchanged by default.
/// }
///
/// // let ast = Parser::parse(...).unwrap();
/// // let mut mapper = RemoveNulls;
/// // let new_ast = mapper.map(&ast);
/// ```
pub trait AstMapper {
    /// Map a `Root` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_root(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `Block` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_block(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `EmptyStatement` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_emptystatement(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `BreakStatement` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_breakstatement(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `Statement` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_statement(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `Assignment` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_assignment(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `DoBlock` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_doblock(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `GotoStatement` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_gotostatement(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `ForStatement` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_forstatement(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `FunctionDeclaration` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_functiondeclaration(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `LocalFunctionDeclaration` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_localfunctiondeclaration(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `LocalAttributeAssignment` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_localattributeassignment(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `IfStatement` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_ifstatement(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `RepeatStatement` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_repeatstatement(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `WhileStatement` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_whilestatement(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `AttributeNameList` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_attributenamelist(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `Attribute` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_attribute(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `LastStatement` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_laststatement(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `Label` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_label(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `FunctionName` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_functionname(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `VarList` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_varlist(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `NameList` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_namelist(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `ExpressionList` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_expressionlist(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `PrimaryExpression` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_primaryexpression(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `PowerExpression` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_powerexpression(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `UnaryExpression` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_unaryexpression(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `MultiplicativeExpression` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_multiplicativeexpression(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `AdditiveExpression` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_additiveexpression(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `StringCatExpression` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_stringcatexpression(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `ComparisonExpression` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_comparisonexpression(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `AndExpression` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_andexpression(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `OrExpression` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_orexpression(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `Expression` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_expression(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `PrefixExp` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_prefixexp(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `FunctionCall` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_functioncall(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `VarOrExp` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_varorexp(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `Var` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_var(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `VarSuffix` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_varsuffix(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `NameAndArgs` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_nameandargs(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `Args` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_args(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `FunctionDef` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_functiondef(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `FunctionBody` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_functionbody(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `ParamList` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_paramlist(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `TableConstructor` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_tableconstructor(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `FieldList` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_fieldlist(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a `Field` node.
    ///
    /// Default: preserve the node kind and pass through mapped children.
    fn map_field(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        mapped_children: &[NodeId],
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: mapped_children.to_vec(),
        }
    }

    /// Map a token leaf node. Tokens have no children.
    ///
    /// Default: preserve the token node unchanged.
    fn map_token(
        &mut self,
        source_id: NodeId,
        source: &Ast,
        _builder: &mut AstBuilder,
    ) -> MappedNode {
        MappedNode::Node {
            kind: source.kind(source_id).clone(),
            children: vec![],
        }
    }

    /// Drive the bottom-up transformation, returning a new `Ast`.
    ///
    /// Walks the source AST in post-order, maps each node via the
    /// appropriate `map_*` method, and assembles the output AST.
    fn map(&mut self, source: &Ast) -> Ast {
        let mut builder = AstBuilder::new();
        let mut node_map: std::collections::HashMap<NodeId, Vec<NodeId>> =
            std::collections::HashMap::new();

        let root = match source.root() {
            Some(r) => r,
            None => return builder.build(source.source().to_string(), source.source_name().to_string()),
        };

        // Post-order traversal: process children before parents.
        let mut stack: Vec<(NodeId, bool)> = vec![(root, false)];
        let mut post_order: Vec<NodeId> = Vec::new();

        while let Some((id, visited)) = stack.pop() {
            if visited {
                post_order.push(id);
            } else {
                stack.push((id, true));
                // Push children in reverse order so first child is processed first.
                let children: Vec<NodeId> = source.children(id).collect();
                for &child in children.iter().rev() {
                    stack.push((child, false));
                }
            }
        }

        // Process nodes in post-order.
        for &source_id in &post_order {
            let mapped = match source.kind(source_id) {
                NodeKind::Token(tid) => {
                    // Copy the token into the builder, preserving its
                    // `TokenSource` variant (original range vs. synthetic text).
                    let new_tid = builder.copy_token(source.token(*tid));
                    let result = self.map_token(source_id, source, &mut builder);
                    match result {
                        MappedNode::Node { kind, children } => {
                            // For tokens, override kind to use the new token id.
                            let actual_kind = match kind {
                                NodeKind::Token(_) => NodeKind::Token(new_tid),
                                other => other,
                            };
                            let node = source.node(source_id);
                            let nid = builder.add_node(actual_kind, node.begin_offset, node.end_offset);
                            for &child in &children {
                                builder.add_child_to(nid, child);
                            }
                            vec![nid]
                        }
                        MappedNode::Splice(nodes) => nodes,
                        MappedNode::Remove => vec![],
                    }
                }
                _ => {
                    // Collect mapped children from the map.
                    let mut mapped_children: Vec<NodeId> = Vec::new();
                    for child_id in source.children(source_id) {
                        if let Some(mapped_ids) = node_map.get(&child_id) {
                            mapped_children.extend(mapped_ids);
                        }
                    }

                    // Dispatch to the appropriate map method.
                    let result = match source.kind(source_id) {
                        NodeKind::Root => self.map_root(source_id, source, &mapped_children, &mut builder),
                        NodeKind::Block => self.map_block(source_id, source, &mapped_children, &mut builder),
                        NodeKind::EmptyStatement => self.map_emptystatement(source_id, source, &mapped_children, &mut builder),
                        NodeKind::BreakStatement => self.map_breakstatement(source_id, source, &mapped_children, &mut builder),
                        NodeKind::Statement => self.map_statement(source_id, source, &mapped_children, &mut builder),
                        NodeKind::Assignment => self.map_assignment(source_id, source, &mapped_children, &mut builder),
                        NodeKind::DoBlock => self.map_doblock(source_id, source, &mapped_children, &mut builder),
                        NodeKind::GotoStatement => self.map_gotostatement(source_id, source, &mapped_children, &mut builder),
                        NodeKind::ForStatement => self.map_forstatement(source_id, source, &mapped_children, &mut builder),
                        NodeKind::FunctionDeclaration => self.map_functiondeclaration(source_id, source, &mapped_children, &mut builder),
                        NodeKind::LocalFunctionDeclaration => self.map_localfunctiondeclaration(source_id, source, &mapped_children, &mut builder),
                        NodeKind::LocalAttributeAssignment => self.map_localattributeassignment(source_id, source, &mapped_children, &mut builder),
                        NodeKind::IfStatement => self.map_ifstatement(source_id, source, &mapped_children, &mut builder),
                        NodeKind::RepeatStatement => self.map_repeatstatement(source_id, source, &mapped_children, &mut builder),
                        NodeKind::WhileStatement => self.map_whilestatement(source_id, source, &mapped_children, &mut builder),
                        NodeKind::AttributeNameList => self.map_attributenamelist(source_id, source, &mapped_children, &mut builder),
                        NodeKind::Attribute => self.map_attribute(source_id, source, &mapped_children, &mut builder),
                        NodeKind::LastStatement => self.map_laststatement(source_id, source, &mapped_children, &mut builder),
                        NodeKind::Label => self.map_label(source_id, source, &mapped_children, &mut builder),
                        NodeKind::FunctionName => self.map_functionname(source_id, source, &mapped_children, &mut builder),
                        NodeKind::VarList => self.map_varlist(source_id, source, &mapped_children, &mut builder),
                        NodeKind::NameList => self.map_namelist(source_id, source, &mapped_children, &mut builder),
                        NodeKind::ExpressionList => self.map_expressionlist(source_id, source, &mapped_children, &mut builder),
                        NodeKind::PrimaryExpression => self.map_primaryexpression(source_id, source, &mapped_children, &mut builder),
                        NodeKind::PowerExpression => self.map_powerexpression(source_id, source, &mapped_children, &mut builder),
                        NodeKind::UnaryExpression => self.map_unaryexpression(source_id, source, &mapped_children, &mut builder),
                        NodeKind::MultiplicativeExpression => self.map_multiplicativeexpression(source_id, source, &mapped_children, &mut builder),
                        NodeKind::AdditiveExpression => self.map_additiveexpression(source_id, source, &mapped_children, &mut builder),
                        NodeKind::StringCatExpression => self.map_stringcatexpression(source_id, source, &mapped_children, &mut builder),
                        NodeKind::ComparisonExpression => self.map_comparisonexpression(source_id, source, &mapped_children, &mut builder),
                        NodeKind::AndExpression => self.map_andexpression(source_id, source, &mapped_children, &mut builder),
                        NodeKind::OrExpression => self.map_orexpression(source_id, source, &mapped_children, &mut builder),
                        NodeKind::Expression => self.map_expression(source_id, source, &mapped_children, &mut builder),
                        NodeKind::PrefixExp => self.map_prefixexp(source_id, source, &mapped_children, &mut builder),
                        NodeKind::FunctionCall => self.map_functioncall(source_id, source, &mapped_children, &mut builder),
                        NodeKind::VarOrExp => self.map_varorexp(source_id, source, &mapped_children, &mut builder),
                        NodeKind::Var => self.map_var(source_id, source, &mapped_children, &mut builder),
                        NodeKind::VarSuffix => self.map_varsuffix(source_id, source, &mapped_children, &mut builder),
                        NodeKind::NameAndArgs => self.map_nameandargs(source_id, source, &mapped_children, &mut builder),
                        NodeKind::Args => self.map_args(source_id, source, &mapped_children, &mut builder),
                        NodeKind::FunctionDef => self.map_functiondef(source_id, source, &mapped_children, &mut builder),
                        NodeKind::FunctionBody => self.map_functionbody(source_id, source, &mapped_children, &mut builder),
                        NodeKind::ParamList => self.map_paramlist(source_id, source, &mapped_children, &mut builder),
                        NodeKind::TableConstructor => self.map_tableconstructor(source_id, source, &mapped_children, &mut builder),
                        NodeKind::FieldList => self.map_fieldlist(source_id, source, &mapped_children, &mut builder),
                        NodeKind::Field => self.map_field(source_id, source, &mapped_children, &mut builder),
                        NodeKind::Token(_) => unreachable!(),
                    };

                    match result {
                        MappedNode::Node { kind, children } => {
                            let node = source.node(source_id);
                            let nid = builder.add_node(kind, node.begin_offset, node.end_offset);
                            for &child in &children {
                                builder.add_child_to(nid, child);
                            }
                            // Recompute offsets from children.
                            if !children.is_empty() {
                                let begin = builder.node(children[0]).begin_offset;
                                let end = builder.node(children[children.len() - 1]).end_offset;
                                builder.node_mut(nid).begin_offset = begin;
                                builder.node_mut(nid).end_offset = end;
                            }
                            vec![nid]
                        }
                        MappedNode::Splice(nodes) => nodes,
                        MappedNode::Remove => vec![],
                    }
                }
            };
            node_map.insert(source_id, mapped);
        }

        // Set root from the mapped root.
        if let Some(mapped_roots) = node_map.get(&root) {
            if let Some(&root_id) = mapped_roots.first() {
                builder.set_root(root_id);
            }
        }

        builder.build(source.source().to_string(), source.source_name().to_string())
    }
}
