// Generated by CongoCC Parser Generator. Do not edit.

use ex2::parser::Parser;

use std::fs;
use std::path::{Path, PathBuf};

/// Recursively collects all files with the given extension under `dir`.
fn collect_files(dir: &Path, extension: &str, out: &mut Vec<PathBuf>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(e) => {
            eprintln!("Warning: cannot read directory {}: {}", dir.display(), e);
            return;
        }
    };
    let mut dirs: Vec<PathBuf> = Vec::new();
    for entry in entries {
        let entry = match entry {
            Ok(e) => e,
            Err(e) => {
                eprintln!("Warning: cannot read directory entry in {}: {}", dir.display(), e);
                continue;
            }
        };
        let path = entry.path();
        if path.is_dir() {
            dirs.push(path);
        } else if path.extension().map_or(false, |e| e == extension) {
            out.push(path);
        }
    }
    // Sort directories for deterministic traversal order.
    dirs.sort();
    for d in dirs {
        collect_files(&d, extension, out);
    }
}

/// Parses all test files matching the grammar's test extension in the
/// test-data directory, asserting that each one parses without error.
///
/// The test-data directory is resolved relative to the crate's manifest
/// directory (i.e., next to `Cargo.toml`).
#[test]
fn parse_test_files() {
    let test_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("test-data");
    if !test_dir.exists() {
        panic!(
            "Test data directory not found: {}\n\
             Expected directory next to Cargo.toml containing test files.\n\
             The build system should copy test files from the grammar's \
             testfiles/ directory.\n\
             Check the build.xml test-rust target for this grammar.",
            test_dir.display()
        );
    }

    let extension = "arith";

    let mut files: Vec<PathBuf> = Vec::new();
    collect_files(&test_dir, extension, &mut files);
    // Sort for deterministic test ordering.
    files.sort();

    if files.is_empty() {
        panic!("No .{} files found in {} — check TEST_EXTENSION setting",
               extension, test_dir.display());
    }

    let mut passed = 0usize;
    let mut failed = 0usize;
    let mut failures: Vec<String> = Vec::new();

    for path in &files {
        let source = match fs::read_to_string(path) {
            Ok(s) => s,
            Err(e) => {
                let msg = format!("Failed to read {}: {}", path.display(), e);
                eprintln!("{}", msg);
                failures.push(msg);
                failed += 1;
                continue;
            }
        };

        let filename = path.file_name().unwrap().to_string_lossy().to_string();
        match Parser::parse(&source, Some(&filename)) {
            Ok(ast) => {
                println!(
                    "OK  {} ({} nodes)",
                    path.strip_prefix(&test_dir).unwrap_or(path).display(),
                    ast.node_count(),
                );
                passed += 1;
            }
            Err(e) => {
                let msg = format!(
                    "FAIL {}: {}",
                    path.strip_prefix(&test_dir).unwrap_or(path).display(),
                    e,
                );
                eprintln!("{}", msg);
                failures.push(msg);
                failed += 1;
            }
        }
    }

    println!("\n{} passed, {} failed, {} total", passed, failed, files.len());

    if !failures.is_empty() {
        panic!(
            "{} file(s) failed to parse:\n  {}",
            failed,
            failures.join("\n  "),
        );
    }
}
