[#var classname = filename[0..(filename?length -6)]]
 /* Generated by: ${generated_by}. Do not edit. ${grammar.copyrightBlurb}
  * Generated Code for ${classname} AST Node type
  * by the ASTNode.java.ftl template
  */

[#var package = grammar.nodePackage]
[#if explicitPackageName??][#set package = explicitPackageName][/#if]

package ${package};

[#if package != grammar.parserPackage]
import ${grammar.parserPackage}.*;
[/#if]

[#if isInterface]

public interface ${classname} extends Node {}

[#else]

[#if grammar.parserPackage?has_content]
import static ${grammar.parserPackage}.TokenType.*;
[/#if]

[#if isAbstract]abstract[/#if]
public class ${classname} extends ${grammar.baseNodeClassName} {}
[/#if]
