[#var classname = filename[0..(filename?length -6)]]
 /* Generated by: ${generated_by}. Do not edit. ${grammar.copyrightBlurb}
  * Generated Code for ${classname} AST Node type
  * by the ASTNode.java.ftl template
  */

package ${grammar.nodePackage};

import ${grammar.parserPackage}.*;

[#if isInterface]

public interface ${classname} extends Node {}

[#else]

import ${grammar.parserPackage}.Token.TokenType;
import static ${grammar.parserPackage}.Token.TokenType.*;

[#if isAbstract]abstract[/#if]
public class ${classname} extends ${grammar.baseNodeClassName} {}
[/#if]
