[#ftl strict_vars=true]
[#var classname = filename[0..(filename?length -6)]]
/* Generated by: ${generated_by}. Do not edit. 
  * Generated Code for ${classname} Token subclass
  * by the ASTToken.java.ftl template
  */
[#var package = ""]
[#if explicitPackageName??]
package ${explicitPackageName};
[#set package = explicitPackageName]
[#elseif grammar.nodePackage?has_content]
package ${grammar.nodePackage};
[#set package = grammar.nodePackage]
[/#if]

[#if grammar.parserPackage?has_content && package != grammar.parserPackage]
import ${grammar.parserPackage}.*;
import ${grammar.parserPackage}.${grammar.constantsClassName}.TokenType;
[/#if]
[#if grammar.parserPackage?has_content]
import static ${grammar.parserPackage}.${grammar.constantsClassName}.TokenType.*;
[/#if]

public class ${classname} extends ${superclass} {
    public ${classname}(TokenType type, ${grammar.lexerClassName} tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }
}