/* Generated by: ${generated_by}. ${filename}${settings.copyrightBlurb} */
[#if settings.parserPackage?has_content]
package ${settings.parserPackage};
[/#if]

import java.util.ArrayList;

// WIP, currently unused

public class CallStack extends ArrayList<NonTerminalCall> {
    
}