/* Generated by: ${generated_by}. ${filename}${settings.copyrightBlurb} */
#if settings.parserPackage
   package ${settings.parserPackage};
#endif

import java.util.ArrayList;

// WIP, currently unused

public class CallStack extends ArrayList<NonTerminalCall> {

}