/* Generated by: ${generated_by}. Do not edit. ${grammar.copyrightBlurb}
 * Generated Code for LexicalState
 * by the LexicalState.java.ftl template
 */
package ${grammar.parserPackage};

public enum LexicalState {
  [#list grammar.lexerData.lexicalStates as lexicalState]
     ${lexicalState.name}
     [#if lexicalState_has_next],[/#if]
  [/#list]
}

