 /* Generated by: ${generated_by}. ${filename} ${grammar.copyrightBlurb} */
package ${grammar.parserPackage};

/**
 * Problem while parsing.
 * TODO. Is a WIP.
 */
public interface ParsingProblem extends Node {
    ParseException getCause();
    String getErrorMessage();
}

