[#ftl strict_vars=true]
 /* Generated by: ${generated_by}. ${filename} */
[#if grammar.parserPackage?has_content]
package ${grammar.parserPackage};
[/#if]

/**
 * Problem while parsing.
 */
public interface ParsingProblem extends Node {
    ParseException getCause();
    String getErrorMessage();
}

