// Generated by CongoCC Parser Generator. Do not edit.

//! Code injections from grammar INJECT blocks.
//!
//! The grammar file contains INJECT blocks that add methods and fields to
//! AST node classes.  In Java/Python/C#, these are inserted directly into
//! per-type class bodies.  In Rust's arena-based AST, there are no per-type
//! structs, so injected code must be adapted to work with `(&Ast, NodeId)` pairs.
//!
//! **How this file is generated:**
//!
//! For each INJECT target in the grammar, `RustTranslator.translateInjectedClass()`
//! attempts a mechanical Java-to-Rust translation.  Code that translates
//! successfully is emitted as Rust; code that cannot be translated is shown as
//! FIXME comments with the original Java source.
//!
//! **What to do with FIXME markers:**
//!
//! 1. Read the original Java code in the FIXME comment.
//! 2. Write an equivalent Rust implementation using the `Ast`/`NodeId` arena API.
//!    See the `child_at()` and `child_is_token()` helpers on `Ast`.
//! 3. Place your implementation in a **separate, non-generated** Rust file
//!    (e.g., `inject_impl.rs`) and add `mod inject_impl;` to a wrapper crate
//!    or binary that depends on this generated library.
//! 4. Alternatively, use `#if __rust__` / `#endif` preprocessor blocks in the
//!    grammar file to provide Rust-native INJECT code that the generator will
//!    include directly.
//!
//! See `FIXME.md` in this directory for a full inventory of needed implementations
//! and an API reference for writing arena-based code.

use crate::ast::{Ast, NodeId, NodeKind};
use crate::tokens::TokenType;

use std::fmt;

// ============================================================================
// EvalError -- error type for expression evaluation
// ============================================================================

/// Errors that can occur during arithmetic expression evaluation.
///
/// Each variant carries a `location` string (from `Ast::location()`) identifying
/// the source position where the error was detected.
#[derive(Debug, Clone)]
pub enum EvalError {
    /// Division by zero encountered during evaluation.
    DivisionByZero {
        /// Source location of the division operator, e.g. "cli:1:4".
        location: String,
    },
    /// A NUMBER token's text could not be parsed as f64.
    InvalidNumber {
        /// The token text that failed to parse.
        text: String,
        /// Source location of the token.
        location: String,
    },
    /// evaluate() was called on a token that is not a NUMBER (should not happen
    /// in a well-formed parse tree, but guarded for safety).
    UnexpectedToken {
        /// The token type name, e.g. "PLUS".
        kind: String,
        /// Source location of the token.
        location: String,
    },
    /// evaluate() was called on a node kind that has no evaluation logic.
    UnexpectedNode {
        /// The node kind name, e.g. "Token".
        kind: String,
        /// Source location of the node.
        location: String,
    },
    /// A required child node was missing from the AST (should not happen in a
    /// well-formed parse tree, but guarded for safety).
    MissingChild {
        /// The parent node kind name.
        parent: String,
        /// The expected child index.
        index: usize,
        /// Source location of the parent node.
        location: String,
    },
}

impl fmt::Display for EvalError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            EvalError::DivisionByZero { location } => {
                write!(f, "division by zero at {}", location)
            }
            EvalError::InvalidNumber { text, location } => {
                write!(f, "invalid number '{}' at {}", text, location)
            }
            EvalError::UnexpectedToken { kind, location } => {
                write!(
                    f,
                    "unexpected token type {} in evaluate() at {}",
                    kind, location
                )
            }
            EvalError::UnexpectedNode { kind, location } => {
                write!(
                    f,
                    "unexpected node kind {} in evaluate() at {}",
                    kind, location
                )
            }
            EvalError::MissingChild {
                parent,
                index,
                location,
            } => {
                write!(
                    f,
                    "missing child at index {} of {} node at {}",
                    index, parent, location
                )
            }
        }
    }
}

impl std::error::Error for EvalError {}

// ---------------------------------------------------------------------------
// INJECT AdditiveExpression
//
// In Java/Python/C#, this code is injected into the AdditiveExpression class body.
// In Rust, the arena model has no per-type class.  Methods below operate on
// Ast and should check that the NodeId has NodeKind::AdditiveExpression.
// ---------------------------------------------------------------------------

// Original Java code (AdditiveExpression):
/*
public double evaluate() {
        double result = get(0).evaluate();
        for (int i=1; i< size(); i+=2) {
            boolean subtract = get(i) instanceof MINUS;
            double nextOperand = get(i+1).evaluate();
            if (subtract) result -= nextOperand;
            else result += nextOperand;
        }
        return result;
    }
*/

// ---------------------------------------------------------------------------
// INJECT MultiplicativeExpression
//
// In Java/Python/C#, this code is injected into the MultiplicativeExpression class body.
// In Rust, the arena model has no per-type class.  Methods below operate on
// Ast and should check that the NodeId has NodeKind::MultiplicativeExpression.
// ---------------------------------------------------------------------------

// Original Java code (MultiplicativeExpression):
/*
public double evaluate() {
        double result = get(0).evaluate();
        for (int i=1; i< size(); i+=2) {
            boolean divide = get(i) instanceof DIVIDE;
            double nextOperand = get(i+1).evaluate();
            if (divide) result /= nextOperand;
            else result *= nextOperand;
        }
        return result;
    }
*/

// ---------------------------------------------------------------------------
// INJECT ParentheticalExpression
//
// In Java/Python/C#, this code is injected into the ParentheticalExpression class body.
// In Rust, the arena model has no per-type class.  Methods below operate on
// Ast and should check that the NodeId has NodeKind::ParentheticalExpression.
// ---------------------------------------------------------------------------

// Original Java code (ParentheticalExpression):
/*
public double evaluate() {
        return get(1).evaluate();
    }
*/

// ---------------------------------------------------------------------------
// INJECT Root
//
// In Java/Python/C#, this code is injected into the Root class body.
// In Rust, the arena model has no per-type class.  Methods below operate on
// Ast and should check that the NodeId has NodeKind::Root.
// ---------------------------------------------------------------------------

// Original Java code (Root):
/*
public double evaluate() {
        return get(0).evaluate();
    }
*/

// ---------------------------------------------------------------------------
// INJECT PARSER_CLASS (Calc)
//
// Parser class injections typically add utility methods (e.g., main()) to the
// parser.  In Rust, the parser is a struct with parsing methods; injected
// methods like main() should be placed in a separate binary crate or test.
// ---------------------------------------------------------------------------

// Note: Parser class injections are shown below for reference.  Methods like
// main() are Java-specific entry points and typically do not need Rust
// equivalents in the library crate.  If you need a Rust binary, create a
// separate bin/main.rs that uses this parser library.

// Original Java code (Calc main):
/*
static public void main(String[] args) throws ParseException {
       String input = "";
       if (args.length > 0)
       {
         System.out.println("Parsing arithmetic expression from the command line");
         input = String.join("\n", args);
       } else {
         System.out.println("Enter an arithmetic expression:");
         Scanner scanner = new Scanner(System.in);
         input = scanner.nextLine();
       }

       PARSER_CLASS parser = new PARSER_CLASS(input);
       parser.Root();
       Node root = parser.rootNode();
       System.out.println("Dumping the AST...");
       root.dump();

       try {
         System.out.println("The result is: " + root.evaluate());
       }
       catch (UnsupportedOperationException e) {
         System.err.println("Failed to evaluate expression. Are you running ex1.Calc? If so, you probably want to run ex2.Calc.");
         System.exit(-1);
       }
    }
*/

// ============================================================================
// Arithmetic expression evaluator
//
// This single impl block consolidates the Java per-class evaluate() methods
// into one Rust method that dispatches on NodeKind.  The arena-based AST has
// no per-type structs, so a match on NodeKind replaces Java's virtual dispatch.
//
// See FIXME.md for the full API reference and translation patterns.
// ============================================================================

impl Ast {
    /// Evaluates the arithmetic expression rooted at the given node.
    ///
    /// Recursively walks the AST, computing the numeric value of the
    /// expression.  Supports addition, subtraction, multiplication, division,
    /// parenthesized sub-expressions, and decimal numbers.
    ///
    /// # Errors
    ///
    /// Returns `EvalError::DivisionByZero` if a division by zero is attempted.
    /// Returns `EvalError::InvalidNumber` if a NUMBER token cannot be parsed.
    /// Returns `EvalError::MissingChild` if the AST structure is malformed.
    ///
    /// # Examples
    ///
    /// ```no_run
    /// use ex2::parser::Parser;
    ///
    /// let ast = Parser::parse("2 + 3 * 4", Some("example")).unwrap();
    /// let root = ast.root().unwrap();
    /// assert_eq!(ast.evaluate(root).unwrap(), 14.0);
    /// ```
    pub fn evaluate(&self, id: NodeId) -> Result<f64, EvalError> {
        match self.kind(id) {
            // Root: delegate to the single child (the top-level expression).
            NodeKind::Root => {
                let child = self.child_at(id, 0).ok_or_else(|| EvalError::MissingChild {
                    parent: "Root".to_string(),
                    index: 0,
                    location: self.location(id),
                })?;
                self.evaluate(child)
            }

            // AdditiveExpression: child(0) (+|- child(i+1))*
            // Children alternate between operands and operator tokens:
            //   [operand0, PLUS/MINUS, operand1, PLUS/MINUS, operand2, ...]
            NodeKind::AdditiveExpression => {
                let first = self.child_at(id, 0).ok_or_else(|| EvalError::MissingChild {
                    parent: "AdditiveExpression".to_string(),
                    index: 0,
                    location: self.location(id),
                })?;
                let mut result = self.evaluate(first)?;
                let count = self.child_count(id);
                let mut i = 1;
                while i < count {
                    let subtract = self.child_is_token(id, i, TokenType::MINUS);
                    let operand_id =
                        self.child_at(id, i + 1)
                            .ok_or_else(|| EvalError::MissingChild {
                                parent: "AdditiveExpression".to_string(),
                                index: i + 1,
                                location: self.location(id),
                            })?;
                    let operand = self.evaluate(operand_id)?;
                    if subtract {
                        result -= operand;
                    } else {
                        result += operand;
                    }
                    i += 2;
                }
                Ok(result)
            }

            // MultiplicativeExpression: child(0) (*|/ child(i+1))*
            // Children alternate between operands and operator tokens:
            //   [operand0, TIMES/DIVIDE, operand1, TIMES/DIVIDE, operand2, ...]
            NodeKind::MultiplicativeExpression => {
                let first = self.child_at(id, 0).ok_or_else(|| EvalError::MissingChild {
                    parent: "MultiplicativeExpression".to_string(),
                    index: 0,
                    location: self.location(id),
                })?;
                let mut result = self.evaluate(first)?;
                let count = self.child_count(id);
                let mut i = 1;
                while i < count {
                    let divide = self.child_is_token(id, i, TokenType::DIVIDE);
                    let operand_id =
                        self.child_at(id, i + 1)
                            .ok_or_else(|| EvalError::MissingChild {
                                parent: "MultiplicativeExpression".to_string(),
                                index: i + 1,
                                location: self.location(id),
                            })?;
                    let operand = self.evaluate(operand_id)?;
                    if divide {
                        if operand == 0.0 {
                            return Err(EvalError::DivisionByZero {
                                location: self.location(operand_id),
                            });
                        }
                        result /= operand;
                    } else {
                        result *= operand;
                    }
                    i += 2;
                }
                Ok(result)
            }

            // ParentheticalExpression: OPEN_PAREN expression CLOSE_PAREN
            // The expression to evaluate is child(1), between the parentheses.
            NodeKind::ParentheticalExpression => {
                let inner = self.child_at(id, 1).ok_or_else(|| EvalError::MissingChild {
                    parent: "ParentheticalExpression".to_string(),
                    index: 1,
                    location: self.location(id),
                })?;
                self.evaluate(inner)
            }

            // Token leaf: must be a NUMBER token.  Parse its text as f64.
            // Operator tokens (PLUS, MINUS, TIMES, DIVIDE) are never passed to
            // evaluate() directly -- they are checked via child_is_token() in
            // their parent expression nodes.
            NodeKind::Token(_) => {
                if let Some(TokenType::NUMBER) = self.token_type(id) {
                    let text = self.text(id);
                    text.parse::<f64>().map_err(|_| EvalError::InvalidNumber {
                        text: text.to_string(),
                        location: self.location(id),
                    })
                } else {
                    let kind_name = self
                        .token_type(id)
                        .map_or("unknown".to_string(), |t| format!("{:?}", t));
                    Err(EvalError::UnexpectedToken {
                        kind: kind_name,
                        location: self.location(id),
                    })
                }
            }
        }
    }

    /// Convenience method: evaluates the root node of the AST.
    ///
    /// Equivalent to `ast.evaluate(ast.root().unwrap())`, but provides a
    /// clearer entry point for callers.
    ///
    /// # Errors
    ///
    /// Returns the same errors as [`evaluate()`](Self::evaluate), plus panics
    /// if the AST has no root node (which would indicate an empty or failed parse).
    pub fn evaluate_root(&self) -> Result<f64, EvalError> {
        self.evaluate(self.root().expect("AST has no root node"))
    }
}
