name: Core Tests

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
        - '**'
        - '!**/*.md'
        - '!.github/workflows/*.yml'
        - '.github/workflows/core-tests.yml'

  pull_request:
    branches: [ master ]
    paths:
        - '**'
        - '!**/*.md'
        - '!.github/workflows/*.yml'
        - '.github/workflows/core-tests.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java-version: ['17', '21']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'oracle'
    - name: Create test directories (POSIX)
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        mkdir -p ~/bin ~/logs
    - name: Create test directories (Windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        $dirs = "${env:USERPROFILE}/bin", "${env:USERPROFILE}/logs"
        foreach ($d in $dirs) {
          if (!(test-path $d)) {
            mkdir $d
          }
        }
    - name: Setup dotnet
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          8.0.x
    - name: Run core tests
      run: |
        git submodule update --init
        ant -version
        ant full-test
